### ISSUE TITLE
New link not displayed when Nightly opens

### ISSUE THREAD

**Issue by sap7772000zilla** [bwinton/TabCenter#1024]
Hello.
Using Nightly 32bit + Tab Center(with 20+ tabs) on Windows 7 64bit.
When the browser is closed and I click on a link (in an e-mail or .pdf document )the browser starts but it is not the page corresponding to the last link that I clicked on that is displayed but one of the "old " ones, usually the last from the bottom; a tab for the desired link is created but kept closed on the top.
Thank you.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @sap7772000zilla and thanks for the report. Can you please do a quick check for me ? In a new tab navigate to about:addons page and select "Extensions" section. After, double click on "Tab Center" extension and reply here with what version are you using.

I'm asking because this issue was reported by me a few months ago and it was fixed in the latest public version (v1.31.0). I just double checked the behavior and it correctly focuses the new tab opened for the external link when browser is launched. At least on Windows 7 x64 and 10 x64 with latest Nightly x32 build.

**Comment by sap7772000zilla** [comment]
Hello.
It seems I have an old one 1.29, last updated in Dec. 2016. The update option is set on "Default" and over the time I saw several changes so I guess it worked up to some point. I changed to "On", will that suffice?
Thank you.

**Comment by sap7772000zilla** [comment]
Hello again.
One night later, after a computer restart I noticed that I'm still on 1.29 so I thought to uninstall/reinstall it to get the last version. Poor judgement, now the addon can't be installed, I get the "Uh oh" message...

**Comment by SoftVision-PaulOiegas** [comment]
Let's see then. What is your Test Pilot add-on version ? I assume you tried to install Tab Center trough it . Currently Test Pilot is at v1.1.2. An older version of Test Pilot could affect the install of experiments.
You should update to latest Test Pilot version first, before attempting to enable Tab Center.

Also, are you using any any antivirus programs ? Like Avast, Kaspersky ? We had some issues in the past with the add-on that is installed by the antivirus client into the browser. In this case you could temporarily disable that add-on and antivirus protection until you install back the Tab Center experiment.

If the issue is still present after this, one of your other installed extensions could be incompatible with Tab Center. You could disable them one by one while trying to enable Tab Center. 
If this is the case, you could inform us what is the one that causes this issue and we could add it to the list of incompatible add-ons for Tab Center.

Please let me know if any of this fixed your issue. If not, we will try to investigate further.

**Comment by sap7772000zilla** [comment]
Hello again.
Once again I had an older version and armed with the same poor judgement I uninstalled it just to notice I can't put it back anymore: the Installing button makes waves for ever even after starting Nightly as Administrator...
I use McAfee antivirus and latest attempts were done with all extensions disabled.
Can I download any of them and do a manual install?
Thank you.

**Comment by sap7772000zilla** [comment]
Hello again.
Once again I had an older version and armed with the same poor judgement I uninstalled it just to notice I can't put it back anymore: the Installing button makes waves for ever even after starting Nightly as Administrator...
I use McAfee antivirus and latest attempts were done with all extensions disabled.
Can I download any of them and do a manual install?
Thank you.

**Comment by SoftVision-PaulOiegas** [comment]
Have you checked also the Test Pilot add-on version ? Having an older version could be the main reason of the issue you encounter.  You can find it also in "about:addons" page at Extension tab and currently Test Pilot is at v1.1.2. 

If you have a lower version, please uninstall it and reinstall the latest one from https://testpilot.firefox.com page.

**Comment by sap7772000zilla** [comment]
Yes. Like I said above, the Test Pilot version was older than indicated and I uninstalled it and hoped to be able to install the latest version available. 
Now I can't put back any version from your site, that's why I asked if I can download it first and manually install it myself.
Thank you.

**Comment by SoftVision-PaulOiegas** [comment]
OK, then I probably wrongly understood what you did in the above messages. 
Please navigate to about:config page, confirm that you accept the risk and in the top text field write "testpilot.env" (without quotes). If that preference has other value than "production" please double click it and change it to that value (no quotes again).
After you do this, try to install Test Pilot again from https://testpilot.firefox.com page. And then try again to enable Tab Center from its page.

Please let me know if this works.

**Comment by sap7772000zilla** [comment]
Hi; the value was "production"  but I still can't install it from your indicated page.
I did 2 more steps:
1. reset the testpilot.env and after this step testpilot.env is not visible anymore
2. noticed that if I filter for "testpilot" only there are 3 more keys visible: browser.addon-watch.ignore / browser.uiCustomization.state / testpilot-addon.install-event-fired and the value of the second has testpilot within.
Needless to say that the Installing... button remains unchanged.
Any other suggestions please?

**Comment by SoftVision-PaulOiegas** [comment]
This is strange 😃. Our options are fewer and fewer. 
Can you please temporary disable McAfee protection ?  After create a new Firefox profile (https://goo.gl/PNe90E - instructions) and retry the install ? 
Maybe on your current profile you have any preferences set that interfere with Test Pilot. Or the antivirus service is blocking the install in some way.

Also, is there a chance that you have any custom Firewall set up on your PC or you are in a network with limited access ?

**Comment by sap7772000zilla** [comment]
I can see we're reaching the bottom here...
I can't disable McAfee and neither I can control the firewall - these functionalities are restricted.
I have created a new profile but I can't open any page, all are declared a security risk and the page is not opened(latest Nightly version) or the tab crashes(Firefox ESR latest 52.1) - that means I can't reach TestPilot page to attempt a new install.

No sources for manually downloading the add-ons?
Thank you.

**Comment by SoftVision-PaulOiegas** [comment]
Then it may be something related to your environment restrictions. A direct link to the signed build I don' think will help you since Firefox won't allow the install from it. 
I could provide you a custom build made from the repository but I'm not sure that will help. I'll try to talk with the developers to see if it's something they can help with on this issue.

Also, one of my team members have found this article related to McAfee 
https://support.mozilla.org/t5/Unblock-Firefox-from-connecting/Update-McAfee-Security-Center-and-firewall-settings-to-allow/ta-p/4456

**Comment by sap7772000zilla** [comment]
I agree with your conclusion, some policy doesn't allow installing apps in the manner provided by your site.
I can still install any item from the Mozilla Addon site ( https://addons.mozilla.org ) and that is the reason why I keep asking about this possibility.
Please thank your colleague for the article but it is useless for me, I can't access theMcAfee interface in the way described there.
Thank you for you patience and willingness to help, I really miss my addons

**Comment by SoftVision-PaulOiegas** [comment]
After discussing with the dev team, it seems that this is a more general issue. I don't think we can do anything to help until it's fixed. You can found out more details here https://bugzilla.mozilla.org/show_bug.cgi?id=1308251.

However, if you have some permissions in the browser you could try to install the experiment from https://testpilot.firefox.com/files/tabcentertest1@mozilla.com/latest . If this is not working either, then I'm afraid that's all I can help you with...

Have a nice day / evening.

**Comment by sap7772000zilla** [comment]
Thank you for your efforts and patience. 
The link helped, both Nightly and FF ESR prevented the site from installing but I found a way to install it manually: it works!
I wish there were a way to be notified when the proper fix becomes available.
Thank you.

**Comment by SoftVision-PaulOiegas** [comment]
You welcome, glad it helped 😃. 

Actually, there is a way to do that and it's quite simple. You can create an account on https://bugzilla.mozilla.org, it's free. Then you navigate to the bug's page and on top right part of it, you'll find a "Follow" button. That option adds you to the CC list and any time there is a change on that bug, you are notified trough email (the one used for the account). 
Sometimes it's a bit of spam, but this way you'll find out exactly when the fix lands.

Have a nice day !
