### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by yesmancan** [bwinton/TabCenter#1049]
Uh oh. ⁨Tab Center⁩ could not be enabled. Try again later.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @yesmancan and thanks for your report. Can you please check something for me first ? Navigate to "about:addons#extensions" page, double click on Test Pilot add-on and tell me what version do you have. 

I'm asking this because we had another case like this where an user got an older version than latest available, that didn't allowed to install experiments. But in his case it was related to the company firewall that was blocking the add-on to update to latest version. 
If the same thing occurs in your case, we are already working on this matter in another issue.

**Comment by yesmancan** [comment]
Thanks @SoftVision-PaulOiegas  greatful
