### ISSUE TITLE
[Nightly] Scroll position not restored after closing full screen

### ISSUE THREAD

**Issue by SpineEyE** [bwinton/TabCenter#1086]
I think Tab Center calls a function that's been [removed a few days ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1364661) which leads to an exception when Tab Center sidebar is expanded. Message in console:

TypeError: this._fillTrailingGap is not a function[Learn More] vertical-tabbrowser.xml:395:15
	handleEvent chrome://tabcenter/content/vertical-tabbrowser.xml:395:15

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @SpineEyE, thanks for the report.
Sadly, as of two weeks ago we no longer support Nightly version 55. ([more info](https://github.com/bwinton/TabCenter/pull/1082))

That being said, I think this issue will be a wontfix. @ericawright, can you confirm?

**Comment by SpineEyE** [comment]
If that's the case, I would like to compile the addon myself, but it seems like the toolchain in this repository doesn't support addon signing and I haven't done this before. I guess, removing the function wouldn't break the behavior in the beta versions but out of the same reason I can't test it.

**Comment by SoftVision-CiprianMuresan** [comment]
I'd suggest using a Mac or Linux to compile the add-on yourself. 
Install NPM and JPM, in a terminal enter the following line "git clone https://github.com/bwinton/tabcenter.git && cd tabcenter/ && npm install && npm run locales && jpm xpi" and press enter.
You can then find the "tabcenter" folder and the an .xpi file inside it.
As you are using Nightly, you don't need to sign the add-on in order to use it. Just set "xpinstall.signatures.required" to false in about:config and just drag and drop the .xpi file in the browser. 

However, this will **not** sign the add-on. It only makes you able to run it on Firefox versions which support unsigned add-ons (Nightly, Dev edition).

**Comment by SpineEyE** [comment]
Thanks, I could restore the correct functionality by removing the one call to the mentioned function.
For anyone else who does this for the first time: I had to remove the official Tab Center and restart Nightly first before installing the locally generated tab-center.xpi . Without restarting Nightly, it seemed to just reinstall or re-enable the original version with the bug.

**Comment by SoftVision-CiprianMuresan** [comment]
You should turn off automatic updates to the add-on because it will keep updating itself to the Test Pilot version.

**Comment by SoftVision-PaulOiegas** [comment]
You can increment the version of the add-on in the "package.json" file, before using "jpm xpi". This will make your custom version the latest and won't update to the current production one.

**Comment by ericawright** [comment]
thank you for the report, but yes, as @softVision-CiprianMuresan said, this will be closed as wontfix.
