### ISSUE TITLE
Feedback: when you have enough tabs for a scrollbar, it pops in and out of existence in a jarring fashion

### ISSUE THREAD

**Issue by chutten** [bwinton/TabCenter#110]
FF47.0b2 on Windows 10

The scrollbar appears and disappears out-of-time with the drawer expansion and contraction. In my opinion, it doesn't look nice. Of course, scrollbars are ugly at the best of time.

**Comment by azdle** [comment]
The scrollbar also causes me problems when trying to quickly click on something. Because there's such a long pause before the area starts expanding and the scroll bar only appears after you mouse over I end up clicking the scroll bar instead of clicking on an actual tab.

![clicking](https://media.giphy.com/media/26vUD22Raw170l7lm/giphy.gif)

I think it would be best to have the scroll bar be anchored to the far side of the "tab box". Even if you want to grab the scroll handle with your mouse cursor, it wouldn't be possible until it's fully expanded and has stopped moving anyway.

**Comment by chris-morgan** [comment]
Just received an update, now it just doesn’t show a scroll bar at all. I guess that’s one way of fixing this issue…

**Comment by bwinton** [comment]
Yep.  I'm closing this for now, but if we re-introduce the scrollbar, we'll take a look at what we can do.  Thanks!
