### ISSUE TITLE
Incompatible with Nightly 56.0a1

### ISSUE THREAD

**Issue by titanous** [bwinton/TabCenter#1104]
I just updated to Nightly 56.0a1 (2017-06-12) on macOS, and the extension was forcibly disabled claiming incompatibility.

**Comment by topaxi** [comment]
Are there any alternatives to this addon for Nightly 56?

**Comment by omeringen** [comment]
@topaxi 
Tree Style Tab

**Comment by bwinton** [comment]
Yes, that's right.  Nightly is changing too much and too quickly for us to commit to supporting it.  We may enable support for 56 when it hits Beta, depending on how much stuff has changed.  In the meantime, I've been suggesting people help contribute to https://github.com/eoger/tabcenter-redux/ which should work on future versions of Firefox.

**Comment by thekyriarchy** [comment]
Why is it changing too much for Tab Center which was a Firefox testpilot lab but not Tab Center Redux? Why is redux a separate project?

**Comment by bwinton** [comment]
It's changing too much because Tab Center is built on an older API that has been removed in Firefox 57 and because Firefox itself is making large changes to greatly improve the speed and responsiveness.

Tab Center Redux is a separate project because it's being built by different people, on the new API, and it's being built as a hobby, not as part of their job.

**Comment by jhasse** [comment]
Check out https://github.com/bwinton/TabCenter/issues/1131#issuecomment-335830960 if you still want to use TabCenter with 56 (not 57+).
