### ISSUE TITLE
Add preference for change in tab size

### ISSUE THREAD

**Issue by JohnAnino** [bwinton/TabCenter#1114]
Hi,
I seem to operate with an average number of tab that fluctuates just above or just under the number that makes the tabs go from big icons to small icons (14 for my screen size/resolution). The result is very frustrating as it keeps changing the size and my tabs keep going up and down.
I would be very useful to able to change this setting in the preferences of the add-on. For instance, one could leave it on "automatic", set a specific number for the change, or prevent changes. In my experience, I would be much happier keeping the icons small at all time, even with very few tabs. 
Thanks for the good work and the great add-on!
Best
J.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @JohnAnino and thanks for your report. However, this can already be done by setting `extensions.verticaltabs.largetabs` = `0` in "about:config" page. We don't have this as an option on the UI because this was not one of the purposes of the experiment. 
Also, I must inform you that the development of the Tab Center was halted for the moment. If you are not aware yet, Tab Center will soon be unsupported by Firefox because it's an SDK based add-on that will no longer work starting with Firefox 56 and 57. 

A decision was not taken yet, if the add-on will return in the future, but you can still use it in Firefox 55 (next release). When it will stop working, you can switch to Tab Center Redux (https://goo.gl/5er5ZE), until a decision is taken for Tab Center.

I will close this issue since we have others logged on the same subject and I think the solution I have provided is exactly what you are looking for. 😃

**Comment by JohnAnino** [comment]
Thanks for the quick feedback, Paul, it's appreciated!

**Comment by SoftVision-PaulOiegas** [comment]
Glad it helped, you welcome! 😃
