### ISSUE TITLE
Disabled in FF56

### ISSUE THREAD

**Issue by adambowles** [bwinton/TabCenter#1115]
![image](https://user-images.githubusercontent.com/10128574/29161682-0ba5179a-7daf-11e7-8eeb-33a2362860ec.png)

**Comment by ur5us** [comment]
@adambowles Look over here: https://github.com/bwinton/TabCenter/issues/1105

**Comment by SoftVision-PaulOiegas** [comment]
Hi @adambowles and thanks for your report. Sadly, Tab Center experiment graduated (experiment ended) and is no longer supported starting with Firefox 56 (still works in latest release Firefox 55). It's unsure yet if the experiment will return after Firefox 57 is released, since it will need to be entirely rewritten as a webextension to work.

However, as @ur5us mentioned in comment above, you can try a similar add-on, [Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/?src=search), that was written from scratch as a webextension. 

I will close this one since it's a known limitation. Anyway, you can sign up for the [Test Pilot Newsletter](https://testpilot.firefox.com/experiments) and watch for any emails with new experiments. Maybe Tab Center will return someday.

**Comment by danielmotaleite** [comment]
If possible, add a upgrade path from the "Tab Center" to "Tab Center Redux" or to [Vertical Tabs reloaded](https://github.com/Croydon/vertical-tabs-reloaded) (even if just a temporary solution for firefox 56) ... even if it is just a text notice in the add-on pages/test-pilot

my Tab Center was disabled with the latest firefox upgrade and had to research what was the result of the pilot experiment and what was the best alternative we had to have again tabs on the sides... not a best experience after a test-pilot, users feel abandoned if no feedback is given for alternatives

**Comment by Croydon** [comment]
> or to Vertical Tabs reloaded (even if just a temporary solution for firefox 56)

As the author of Vertical Tabs Reloaded I can assure you that VTR will work with FF57+ as well. I'm working to rewrite it as a WebExtension. More information at https://github.com/Croydon/vertical-tabs-reloaded/issues/13

**Comment by jhasse** [comment]
Check out https://github.com/bwinton/TabCenter/issues/1131#issuecomment-335830960 if you still want to use TabCenter with 56 (not 57+).
