### ISSUE TITLE
compact view as a setting

### ISSUE THREAD

**Issue by alrick** [bwinton/TabCenter#1117]
It would be nice to be able to chose the compact view (triggered when there is a lot of tabs) even for a small number of tabs. As an option of the add-on settings.

**Comment by alrick** [comment]
Seems like it's possible in the about:config of Firefox.
Preference name : `extensions.verticaltabs.largetabs`, set it to `0`

It would be nice to have it as a standard option :)

**Comment by bwinton** [comment]
Given that the extension is going to stop working in early November, and given that every option doubles the amount of testing and edge cases, I'm not really enthused about adding official support to this option, so I'm gonna close this issue. But thank you for filing it! It's always nice to know what people are looking for, even if I'm not going to give it to them 😉

**Comment by alrick** [comment]
Thanks for your reply.
Can I ask you about the fact the extension will stop working in early november? I know this is an extension experiment but why completely removing it and not let it as is? I'm addicted to this gem :D

**Comment by bwinton** [comment]
Yeah, sure!

The reason it'll stop working is because it's a XUL-based add-on, using the Add-on SDK, and we're shutting off support for XUL-based add-ons in Firefox 57, and have already removed a bunch of the Add-on SDK code.  (The trade-off is that this allows us to make Firefox _way_ faster, and make changes much easier, and have it crash far less.)

I've mostly switched to [Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/), which is built on a new standard API for writing cross-browser extensions.  It's not exactly the same, but it's amazing how close its gotten with far less work, and it's way easier to add some of the features we just couldn't put in this version.  🙂  Give it a try, and if there's stuff it doesn't do, you can [file issues](https://github.com/eoger/tabcenter-redux/issues) on its repo.
