### ISSUE TITLE
Not compatible with firefox dev edition v57.0x

### ISSUE THREAD

**Issue by zzxqd** [bwinton/TabCenter#1128]
![default](https://user-images.githubusercontent.com/23022401/30998040-712dd450-a4fe-11e7-9645-9b7f5103cb63.png)

**Comment by zzxqd** [comment]
Please tell me how can i use it ,i like it  which make tabs on firfox look like such as on vivaldi!

**Comment by zzxqd** [comment]
And could you can make it better with suitability for multi tabs(more than 10)and min-width(with close button when hover)

**Comment by zzxqd** [comment]
![default](https://user-images.githubusercontent.com/23022401/30998187-66bb38ea-a4ff-11e7-9a6e-11068fc66cef.png)
just like vivaldi,
Thanks for your worked.It's awesome!

**Comment by bwinton** [comment]
I'm afraid it just won't work with Firefox 57. The APIs it uses have been removed, so that the whole browser can go faster. But, there's a new project that re-implements the feature with the new APIs, [over here](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/)!

Thanks for using TabCenter, and I hope you like the replacement. 🙂
