### ISSUE TITLE
Incompatible with FF 56.0

### ISSUE THREAD

**Issue by papanito** [bwinton/TabCenter#1129]
The plugin is not compatible with FF 56.

Affected version: TabCenter 1.36.00

**Comment by SoftVision-PaulOiegas** [comment]
Hi @papanito and thanks for your report. Unfortunately Tab Center experiment ended back in July (07/12) but the dev team allowed it to still work until Firefox 55. 
It was already doomed to stop working in Firefox 57 when the APIs for SDK based add-ons will be removed in favor of Webextension add-ons, so the browser to be more safer and faster. Therefore was no point in maintaining it since it needs to be entirely rewritten.

However, there is an alternative that you can try, which was written from scratch as a webextensions. [Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/) is based on the original idea of Tab Center, but it's still a work in progress. So you won't find all the features from the original, but still it's a good alternative.

**Comment by papanito** [comment]
Thanks for your feedback and your recommended alternative, will check it out. 
Btw. I really liked your Tab Center experiment

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, me too... But maybe if we ask @bwinton pretty hard, he will reconsider. 😆 
I'm kidding, for the moment there is no plan in the direction of rewriting it, but keep an eye on the [Test Pilot page](https://testpilot.firefox.com). Maybe the team will reconsider this after the Firefox 57 November release.

**Comment by bwinton** [comment]
You can ask as hard as you want, the APIs still won't be there. 😄

But I've been contributing to Tab Center Redux, and it's looking pretty good, and getting better all the time!

**Comment by jhasse** [comment]
Check out https://github.com/bwinton/TabCenter/issues/1131#issuecomment-335830960 if you still want to use TabCenter with 56 (not 57+).
