### ISSUE TITLE
It is not compatible with Firefox 56.0

### ISSUE THREAD

**Issue by cesarfp** [bwinton/TabCenter#1131]

**Comment by bwinton** [comment]
Nope, and it's very incompatible with Firefox 57, so it's unlikely we're going to fix it. [Tab Center Redux](https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux/) is what we're suggesting people install instead.  Thanks!

**Comment by jhasse** [comment]
Tab Center Redux isn't a replacement (tab bar still shown, also https://github.com/eoger/tabcenter-redux/labels/D-tabcenter-parity). Why are you doing this? You are hurting a lot of people, who want to stay with 56 because they are using several extensions which don't work with WebExtensions yet.

**Comment by bwinton** [comment]
@jhasse There is already a bug filed for the tab bar still being shown. I expect it will get fixed when someone gets around to working on it (or sooner if a contributor picks it up).

I apologize if you thought that this experiment was going to be supported forever. That was never the intention, and since the experiment is over, it doesn't make a lot of sense for me to spend my limited time keeping it up to date instead of working on things which will benefit far more people, particularly since it would need a complete re-write to work in Firefox 57.

From what I've seen, most add-ons with active maintainers have been or are being ported to the new WebExtensions API (although some people _are_ waiting until the last second to do it), so staying on 56 shouldn't be necessary by the time 57 is released, and I strongly recommend against it both from a security point of view, and because you'll be missing all the hard work that has gone into making 57 much, much faster and more stable than 56.

**Comment by jhasse** [comment]
Thanks for the answer. 

> There is already a bug filed for the tab bar still being shown. I expect it will get fixed when someone gets around to working on it (or sooner if a contributor picks it up).

I'm following the bug report and it has beens said that the fix won't make 57. 58 is also very unlikely. People are bagging for the next Extended Support Release at least.

Native menus will take even longer! Redux also has theming issues and doesn't work with tab groups. There's other small annoyances, but I could live with them. The missing button to switch between vertical tabs *only* and normals tabs is a blocker though.

> I apologize if you thought that this experiment was going to be supported forever.

I didnt think that ;) It has been communicated pretty often that some extensions might break with 57.

Here's the thing though: I never expected TabCenter to disappear with 5**6**.

Please reconsider pushing a version for 56. I guess it should work better than TabCenter Redux? I'll test later with compatibility check disabled.

**Comment by bwinton** [comment]
I've re-considered it, but the experiment ended a while ago, and putting more work into the add-on isn't a good use of my time. You're free to download the code, and build it yourself with the maxVersion set to 56. (I'll be glad to help you get that working if you want! Email me at bwinton@mozilla.com, so that we can keep this bug on-topic.) And since we aren't going to update the version on addons.mozilla.org, your custom build won't be overwritten, so it should continue to work until you upgrade. 🙂

**Comment by jhasse** [comment]
If all it takes would be to bump maxVersion, I would be great if the version on addons.mozilla.org could be updated one last time so that not everyone has to build the code himself.

**Comment by bwinton** [comment]
It's bumping the number and testing all the various combinations of functionality to make sure everything still works, which is a surprising amount of work. Also, does addons.mozilla.org even support uploading old-style add-ons anymore?

**Comment by jhasse** [comment]
> and testing all the various combinations of functionality to make sure everything still works, which is a surprising amount of work.

You wouldn't need to do that as everything is better as not working at all ;)
Anyway I would volunteer to do that testing :)

> Also, does addons.mozilla.org even support uploading old-style add-ons anymore?

Good question.

**Comment by bwinton** [comment]
>> and testing all the various combinations of functionality to make sure everything still works, which is a surprising amount of work.

> You wouldn't need to do that as everything is better as not working at all ;)

You say that, but I'm the one who gets all the complaints when stuff doesn't work. :wink:

**Comment by jhasse** [comment]
> You say that, but I'm the one who gets all the complaints when stuff doesn't work. 😉

Well you're getting complains now, because 100 % of the functionality isn't working: #1104 #1107 #1108 #1110 #1115 #1129 #1130 #1131

I've installed https://addons.mozilla.org/de/firefox/addon/checkcompatibility/, but I couldn't find a way to get TabCenter again (I guess I should have installed that addon before updating to 56). Do I need to build from source or could you point me to a link for the xpm?

**Comment by bwinton** [comment]
You need to build from source, I'm afraid. There are instructions [here](https://github.com/bwinton/TabCenter#development) that should get you up and running.

**Comment by jhasse** [comment]
Okay tried that (had to use `./node_modules/jpm/bin/jpm xpi` instead of `jpm xpi` though). Now I have an xpi file, but I can't install it, since it isn't signed. Any way around that?

Btw: Another one for the list: #1132

**Comment by bwinton** [comment]
If you change the `xpinstall.signatures.required` pref (in `about:config`) to `false`, you should be able to install it.

**Comment by jhasse** [comment]
That has worked, thanks!

What are the chances of you pushing the 46-compatible version to amo? So far everything works as before. I'm very happy but I would like to help out other TabCenter users, too (especially those not able to figure out `npm`, Git, etc.).

**Comment by bwinton** [comment]
Given that the existing add-on isn't on AMO, the chances are very small. But feel free to point other people to this thread, so that they can follow the same steps you did (or post your version of the add-on somewhere and I'll be happy to point people at it)!

**Comment by jhasse** [comment]
Okay, that's sad to hear. I'll switch to a different browser when 57 comes out anyway though.

Here's the file if other people want to use TabCenter with 56: [tab-center.zip](https://github.com/bwinton/TabCenter/files/1375926/tab-center.zip) (extract, set `xpinstall.signatures.required` to false in `about:config`, drag'n'drop xpi over Firefox)

**Comment by bwinton** [comment]
While I'm here, is the still-showing-top-tabstrip the only thing you feel is missing from Tab Center Redux, or were there other things?

**Comment by jhasse** [comment]
That and the two bugs mentioned here: https://github.com/eoger/tabcenter-redux/labels/D-tabcenter-parity

You might think that a native context menu isn't important, but I'm on Linux and there you can hold down the right mouse button and select an entry by releasing it, which is something I use all the time.
I also drag tabs off to move them to a new windows. Using the context menu has the disadvantage that I can't immediately select the monitor / workspace where the new window should appear.

I also like the fact, that TabCenter goes to the very top, maximizing the vertical space for tabs.

**Comment by jhasse** [comment]
I've created a new issue for that last one: https://github.com/eoger/tabcenter-redux/issues/198

**Comment by SoftVision-PaulOiegas** [comment]
@jhasse I think the drag and drop for new window and bookmarking was already fixed in my issue #176. Haven't created an xpi from the repo to check if it's fixed yet. 

@bwinton Also I want to add to the list:
1. The "reverse tabs order" is something that I miss very much in TC Redux. That feature helps a lot with the pinned tabs since they do not persist when scrolling the tabs list.
2. Resize to minimum and auto-hide options.

**Comment by bwinton** [comment]
Pinned tabs do persist in TC Redux (or will in the next release)… Also, (as I suspect you know better than most), the Reverse Tab Order was the cause of no end of problems and bugs! 😉

Resize to minimum and auto-hide would be nice. Could you file a bug for a WebExtension API to enable that?

**Comment by SoftVision-PaulOiegas** [comment]
Yeah, I agree on the reverse tabs order feature. Great news, if the pinned tabs will persist in the next release, probably users won't feel the need of it so much (at least I think I won't).

Sure thing, I'll file one for the resize and auto-hide. 👍

**Comment by SoftVision-PaulOiegas** [comment]
@bwinton, here it is, hope I haven't said something wrong. 😄 
https://bugzilla.mozilla.org/show_bug.cgi?id=1408077
