### ISSUE TITLE
Allow less-tall tabs

### ISSUE THREAD

**Issue by jdashg** [bwinton/TabCenter#253]
Many other vertical tabs extensions have much more compact (height-wise) tabs.

There should be an option for either choosing a new size, or just a 1.5xline-size 'compact tabs' option.

**Comment by jasonmobley** [comment]
I have a local branch that adds a pref for tab size with two options: Normal and Compact. I started working on it before #401 appeared, so I'm not sure how this issue fits in with that. Is this issue still relevant?

**Comment by bwinton** [comment]
Hmm, I'm not sure.  I don't think we'll be adding a smaller-than-favicon size, so if that's what you're going for, then your branch probably makes sense.  On the other hand, it's unlikely we'll merge that patch in to this version of Tab Center, since it's not something we think will be of interest to most people (and we're trying to avoid prefs where possible).  So I would probably keep your branch, if I were you, and try to update it to work with the new code…  (I think we're mostly done with the large UI changes, at least until we test it some more.)

**Comment by bwinton** [comment]
And there's now a hidden pref to show favicon-sized tabs, which I think is as small as we're going to make them.  Thanks!
