### ISSUE TITLE
Addon buttons are no longer displayed in "New Tab" section

### ISSUE THREAD

**Issue by ArcFutahito** [bwinton/TabCenter#357]
Previous versions of Tab Center had this great ability to have addon buttons after "New Tab" when expanded. Now it's not working anymore. 
Why would you ever disable something so great?

**Comment by ericawright** [comment]
Well, we haven't decided on where to put those buttons yet, so in the meantime they are hidden. See PR #311 and issues #4 and #304

**Comment by Celti** [comment]
I just (like, ten minutes ago) started using Tab Center after joining Test Pilot, and this is the key feature I'm missing, because I *also* use the Simplified Tab Groups extension. With vanilla Firefox/Aurora, I have the tab groups button on the end of my tab bar, but Tab Center currently offers me no way to customise its appearance and what buttons it offers.

Besides that they seem to work quite well together, so I will just keep the tab groups button at the beginning of my toolbar instead, until this issue is resolved.

**Comment by bwinton** [comment]
Resolved "By Design", I'm afraid…  Thanks for the suggestion, though!
