### ISSUE TITLE
UX: thinner tabs makes selecting tabs a bit harder

### ISSUE THREAD

**Issue by armenzg** [bwinton/TabCenter#377]
With the normal tabs, you don't need to be very precise to click on a tab. There is a wide area that is easy to click on.

With Tab Center I have to focus and make sure that the mouse is hovering precisely over the tab I care to select.

**Comment by Nolski** [comment]
As far as UX goes, I feel like I haven't had too much trouble here. The size of each tab is larger than the size of the omnibar.

**Comment by armenzg** [comment]
Is the omnibar the default tabs?

In Tabs Center you have small height to select a tab compare to the large width of the tabs.

It's been problematic for me. Perhaps it becomes more obvious when using the trackpad of my thinkpad.

**Comment by Nolski** [comment]
The omnibar is the the url bar.

**Comment by mlissner** [comment]
I'd actually expect this to be a big improvement over regular tabs. [Fitt's Law][1] says that larger things are easier to hit, and also that the direction of movement plays a big role. So, for example, it's easier to hit a long horizontal target from the left or right than it is from above or below. 

As this applies here: in traditional tabs, you're trying to hit a horizontal target from below -- this is actually pretty bad, because it's easy to go too far and miss the target. With Tab Center, you're trying to hit a horizontal target from the right -- this is much better! 

The other fun part of Fitt's Law is that things that are on the edges of the screen are considered infinitely large because you can throw your mouse to the edge of the screen and you can't miss the target -- at least not left/right. This is considered a really good thing, and it's a great feature of Chrome's tabs -- if you throw your mouse to the top of the screen, you only have to focus on the left/right position of your cursor. Tab Center shares this advantage, because if you throw your mouse to the left, you only have to focus on the up/down aspect of your cursor. 

All this to say: Tab Center should be much better than regular tabs. I think we should close this issue! 

Here's some more on it too: https://blog.codinghorror.com/fitts-law-and-infinite-width/

[1]: https://en.wikipedia.org/wiki/Fitts%27s_law

**Comment by bwinton** [comment]
That would be true, but I claim that for most people their tabs are at the top of their screen, thus making it a large horizontal space, and infinite vertical space when hitting from below.  Tab Center has a (much) smaller vertical space, but infinite horizontal space when hitting from the side.  So the tabs do end up being harder to hit.  Having said that, the Thumbnail view makes the tabs almost double the height for most people, which helps mitigate this a little.

**Comment by mlissner** [comment]
OK, I'm out of touch! I didn't realize Firefox moved the tabs all the way to the top on Windows these days -- I thought the title bar was still there by default, like it is on Linux, which I use. I agree with your point. 

That said....is there anything that we can do here to fix it?

**Comment by bwinton** [comment]
I don't think there is without massively compromising the design, so I'm going to close this.  🙂
