### ISSUE TITLE
Option to open links at top or bottom

### ISSUE THREAD

**Issue by kkot** [bwinton/TabCenter#410]
For new tabs there is option if new tab should be at top or bottom but opened links (for example from Outlook or some IM) appear at bottom. It should be able to configure it so that older tabs are always at bottom or top depending on preferences of user.

**Comment by mlissner** [comment]
I've wondered if they should just open at the bottom and we could thus avoid having a setting.

**Comment by kkot** [comment]
Because pinned tabs are current not pinned (they stay at top), I would prefer to have all new tabs at top and older ones at bottom so that I don't need to scroll.

**Comment by bwinton** [comment]
So, there are a few different ways we get new tabs:

1. Clicking the “New Tab” button (or pressing `Ctrl-t`/`⌘-t`).
1. `Ctrl`-clicking/`⌘`-clicking on a link on a web page.
1. Clicking a link in an external application.

And there are (currently) two options:

1. Open new tabs on top.
1. Don't open new tabs on top.

So that gives us the following table:

 | Open on Top | Don't Open on Top
------------ | ------------ | -------------
New Tab Button |  | 
Link in Page |  | 
External App |  | 

Suggestions for what to do in each case would be welcome.  🙂

**Comment by mathroc** [comment]
my preferences:

| | 	Open on Top | 	Don't Open on Top |
------------ | -------------|------------------|
| New Tab Button 		| open on top | open on bottom |
| Link in Page 		| open just on top of current tab* | open below current tab* |
| External App 		| open on top | open on bottom |

* if I open multiple tabs, they should open after the previously opened tab (1st opened tab is adjacent to current one, 2nd tab is next, etc. - same behavior as currently)

**Comment by kumar303** [comment]
These would be my preferences as well ^

**Comment by mlissner** [comment]
The above looks good to me too, except I wouldn't expect a "link in page" to open a tab above the current tab. That seems wickedly weird to me -- maybe I'm misunderstanding. I'd expect clicking a link in a page to always open it below the current tab.

**Comment by kkot** [comment]
I agree with @mlissner. Opening "link in page" above would be probably confusing (but maybe would just require getting used to it). But in general proposition from @mathroc looks good.

**Comment by lkraav** [comment]
Oh sweet. I think this might render https://github.com/zeird/tabcontrol obsolete.
