### ISSUE TITLE
Option to turn off the newest style change

### ISSUE THREAD

**Issue by tobia** [bwinton/TabCenter#439]
The latest update turned on a new multi-line tab style with website thumbnails:

![screen shot 2016-07-22 at 11 06 15](https://cloud.githubusercontent.com/assets/48756/17052113/5bee45fa-4ffc-11e6-9bc0-be715e648d34.png)

I personally don't think it looks very good, in fact I much preferred the old style. 

In addition to the looks, which is of course subjective, I also find it a bit too "cluttered," in that it makes it more difficult to visually "skim" through the list to find the tab you're looking for. Finally, I think it wastes too much space. 

When I saw the change, I looked for an option to turn it off, and I was kind of disappointed there was none (not even a hidden setting in about:config.)

But I also understand this is project is a beta where experiments are exactly supposed to happen, and that settings take time and effort to code and test. So I'll just downgrade my plugin to the previous version for the time being, because for me this change was a net loss in usability. 

Hope this helps. Keep up the good work!

**Comment by danfarrow** [comment]
I'm also not a fan of the thumbnail previews & would appreciate a way to switch to icons. 

It seems like a good idea on paper, but in practice they make the collapsed vertical tab display look messy, cluttered & confusing

![vertical-tabs](https://cloud.githubusercontent.com/assets/236580/17052808/f29d0834-4ff6-11e6-8a78-8725c2d71de2.png)

**Comment by tobia** [comment]
[Here is a download link](https://www.dropbox.com/s/7q5f3kbeyg8j7ee/tabcentertest1%40mozilla.com.xpi) if others want it, since I can't find a release history page, neither here nor in addons.mozilla.org (that's another issue with this test pilot thing…) The file installs cleanly since it's already signed.

Come on, you must admit this looks way better:

![screen shot 2016-07-22 at 11 15 19](https://cloud.githubusercontent.com/assets/48756/17052412/a26f8f60-4ffd-11e6-977d-3109f510bed6.png)

**Comment by rpichot** [comment]
I agree - especially when working in the 12-15 tabs range, switching automatically from the small-thumbnails to the large-thumbnails back and forth is quite confusing. I would definitively vote for an option to turn it off.

**Comment by pvsomebody** [comment]
I like the new style well enough, but I have to add my 2 cents to the discussion, -- sometimes the old one worked better, particularly if you have a lot of tabs open. Please add an option to revert it.

**Comment by gdgetguru** [comment]
I agree I am not a fan of this new layout. I am sure some people would like it but it should be an option. Not an all or nothing. To me this does not look very clean and looks jumbled.  Please give option to revert back.

**Comment by folz** [comment]
Going to agree with folks above, for three reasons

1) Screenshots of documentation pages, google docs, github issues, etc look identical at low resolution. The title snippets from the previous version were usually enough to differentiate, but now I'm unable to tell these pages apart without mousing over the tab sidebar until it expands.

2) Like someone else mentioned, the opening and closing a thirteenth tab causes the expand/contract animation to trigger every time, which is very distracting to me.

3) There is very little visual distinction between where one tab preview stops and the other starts, especially if the page has a white or off-white background.

- - -

@tobia, one small bit of unsolicited feedback: it doesn't feel good when someone tells you your work is "horrible", "awful", and "very ugly". Blake and Erica have been working on this for months now, and their work has made me (and probably many others) much more productive. This time they made a mistake and their change didn't match our expectations for what sidebar tabs mean. Let's give feedback on why this change isn't helpful to us, instead of attacking them for trying something new.

**Comment by ArcFutahito** [comment]
1) URL link is completely useless because most of the links are too long to be displayed fully and the end of link is the meaningful part, not the beginning. (Let's just be honest, someone decided to stick them in there because list looked too spaced out with previews, not because it provides any kind of help)
2) Page previews are useless at this size because they don't provide any kind of meaningful information. Icons are good enough to differentiate between websites.
3) Tab entries are too fat and not, instead of easily fitting 30> tabs it can barely fit in 20 and tab center was supposed to make managing tabs easier. 

I don't see how you can be much more productive with this update. Experiments are good and all but common sense should be applied too.

**Comment by tobia** [comment]
@folz you're right of course. I edited my post to better convey my meaning. 

I think Blake and Erica have been doing a tremendous job with this project! A big **thank you** from me! Their work has already made a big impact on the large amount of time I spend in front of the browser at work and I'm sure that's true for 1000s of other users!

**Comment by konfou** [comment]
I find thumbnails unnecessary though I don't mind the links. Nevertheless both could be useful on occasions so having an option to activate/deactivate them will be nice.
For those that find the newer style distracting, it only appears as long there is free space. So open a bunch of new:tabs until it switches to the old style.

**Comment by danfarrow** [comment]
The new (today) borders & drop-shadows on the thumbnails make them much more readable & easier to navigate. I'd still welcome an option to switch them off though

**Comment by seanwhite** [comment]
Have the same experience. I very much appreciate the work here & happen to prefer the simple previous version. Looking forward to the option.

**Comment by Keith94** [comment]
To disable them in the next version, go to about:config and set `extensions.verticaltabs.largetabs` = `0`

**Comment by lkraav** [comment]
Is there a way to get signed nightly master releases? Last release was 14 days ago.

**Comment by Keith94** [comment]
I don't think so, but you can set `xpinstall.signatures.required` = `false` in about:config, and build the XPI using node.js command prompt.

I uploaded latest master build if you want to test it: https://mega.nz/#!D4JwhbgY!_Scd1nDc205BLkC0p6uvP1G4OJ5793XZgF37jZOWyMo

**Comment by lkraav** [comment]
`xpinstall.signatures.required = false` is not applicable to release FF builds, as far as I can tell from https://wiki.mozilla.org/Add-ons/Extension_Signing FAQ section.

**Comment by bwinton** [comment]
You can load them (until you restart) by going to `about:debugging`, clicking the “Load Temporary Add-on” button, and choosing the XPI.  Or you could wait until Friday, which is when we plan on releasing the next version.  🙂

**Comment by lkraav** [comment]
> Or you could wait until Friday, which is when we plan on releasing the next version.

Something blocked the release or just github tag missing?

**Comment by bwinton** [comment]
The release is blocking on another issue.  I'm hoping it'll be resolved today.

**Comment by mlissner** [comment]
Any chance the `extensions.verticaltabs.largetabs = 0` setting can get documented or added to the interface?

I just refreshed Firefox and had to dig out this issue to remember how to do this.
