### ISSUE TITLE
When closing a tab, other tabs should not resize until cursor leaves sidebar region

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#520]
Just like the default behavior with horizontal tabs [(bug 465086)](https://bugzilla.mozilla.org/show_bug.cgi?id=465086), closing the tabs near the bottom should not automatically resize the tabs, so that we can close them more easily without having to move the cursor.

**Comment by ericawright** [comment]
this is being addressed in #497

**Comment by Keith94** [comment]
Mm this bug is actually different (if you read bugzilla link I posted), it affects small tabs mode too...

**Comment by CharoSW** [comment]
This bug is still there.  When you are closing a enough tabs that they should resize, they do so while your cursor is still in the sidebar where you are possibly still closing tabs.  This is especially annoying if you are closing tabs that aren't at the top as suddenly your cursor is now over another tab rather than the one you wanted to close.  Expected behavior should be that the resize shouldn't happen untill you've moved your cursor out of the sidebar, which is indicative that you have finished your changes.
