### ISSUE TITLE
tab title not readable with developer edition dark theme.

### ISSUE THREAD

**Issue by jbhoosreddy** [bwinton/TabCenter#521]
Trying tab center again but the theme for developer edition doesn't work with it, mainly the tab title is hard to read.

<img width="283" alt="screen shot 2016-08-12 at 11 23 40 am" src="https://cloud.githubusercontent.com/assets/2481105/17632578/02a6afc2-607e-11e6-86c2-58054a4b37bd.png">

**Comment by bwinton** [comment]
This _should_ be fixed in the next release, but if you wanted to double check, you could download [this version](https://dl.dropboxusercontent.com/u/2301433/Firefox/VerticalTabs/tab-center.xpi), then go to `about:debugging`, and load it with the "Load Temporary Add-on" button.  (But be sure to disable your current Tab Center add-on first!  🙂)

I'm going to close this now, but please re-open it if your testing reveals that the next release doesn't fix it!  And thanks for the report!
