### ISSUE TITLE
Make preview images optional

### ISSUE THREAD

**Issue by 6a68** [bwinton/TabCenter#526]
@bwinton Hey, filing this bug because users are asking for it in this Discourse thread:

https://discourse.mozilla-community.org/t/revert-to-just-text-on-left/9875/

Is it possible to disable preview images? Maybe a pref with a checkbox to shut 'em off?

**Comment by bwinton** [comment]
Hey @6a68, we're not going to do this, I'm afraid.  It _would_ be easy, but it's not what we're interested in exploring in this experiment.  (Maybe after it graduates from Test Pilot we'll re-visit the decision, but in the meantime I'ld rather fix the problems people are reporting with  thumbnails instead of just disabling them entirely.)

Thanks for the report!  :smiley:
