### ISSUE TITLE
Tab center never installs

### ISSUE THREAD

**Issue by mrapps** [bwinton/TabCenter#602]
Hi,

I'm running 48.0.2 in windows 7 enterprise and Tab Center never installs (i've tried on successive versions since 47.0)

I just get: Uh oh. ⁨Tab Center⁩ could not be enabled. Try again later.

Other Test Pilot experiments all install without issue.

**Comment by SoftVision-PaulOiegas** [comment]
Hi mrapps,

We have tried to reproduce this issue and could not replicate it on latest Firefox release using a machine with Windows 7 (x64). Are you trying to install the add-on from from https://testpilot.firefox.com web page ?

Also can you please let me know if this issue reproduces on a new profile and in safe mode ? Maybe you have some other installed add-ons that are making Tab Center installation impossible. You can find details here for the above setup https://goo.gl/PNe90E .

**Comment by mrapps** [comment]
Hi,

Thanks for responding. I’ve tried again on a new profile and still get the same behaviour. Under this profile i only have one other (disabled) add-on related to McAfee but I can’t remove that. 

All the other testpilot add-ons install ok so I suspected it was something specific that the install was requesting. I’m behind a corporate firewall.. could the install or a part be being blocked - note that i’m going to https://testpilot.firefox.com ok so I’m not sure what WOULD be being blocked!

Thanks again

**Comment by SoftVision-PaulOiegas** [comment]
Both the firewall or the antivirus could be a good reason for this but I can't be sure. We have found recently some issues with Test Pilot add-ons that were not working because of other 3rd party add-ons previously installed. In the future we will display a list of conflicts if we detect users have any.

However, a new profile means no extensions, no custom Firefox settings so we eliminated this possible causes. Probably the only way to check this would be to test on a computer outside that network to be sure that the Firewall isn't affecting in some way.

Also, can you do one more check and test the same scenario on the latest Firefox Nightly build ? It's a small chance but you never know. Maybe the installed browser you use has some problem. Here is the link (https://nightly.mozilla.org/) from where to get it if you have time to test. Maybe it was an issue that was fixed recently.

**Comment by mrapps** [comment]
Hi

I've been able to bypass the firewall and the add on now installs fine. Thanks for your assistance
