### ISSUE TITLE
Inaccurate preview.

### ISSUE THREAD

**Issue by Red-Squid** [bwinton/TabCenter#630]
Why is it that the tab list looks so nice and clean and efficient on the Test Pilot webpage, but then is actually heavily cluttered and inefficient when installed?

Examples: http://imgur.com/a/TDuBq

Where are the on/off options for the thumbnails (unloaded pages show nothing anyway), or the cluttering and excessive web-domain tab subtitles (just why?--show them on a mouse-over popup!)?

Some people might find those 2 features useful (sometimes), but otherwise they are just over-complicating an otherwise useful add-on. The thumbnails are way too small, and they are 1/4th covered by the Favicon anyway; and both the thumbnail and web-domain info would be more useful if pushed to an 'optional' mouse-over info-card pop-up.

Perhaps provide options:

- Tab info detail -- low (just title) -- medium (title + web-domain subtitle) -- high (title + web-domain + thumbnail)
- Info card detail (on mouse-over pop-up): -- low (default; title only) -- medium (title from tab + web-domain info) -- high (title from tab + web-domain info + thumbnail)
- Info card size -- small -- medium -- large -- manual size box (in pixel width)

Some other 'always useful' features may be: tab trees (tree families/groups, like file browsers), a 'bookmark this tree' context menu option, or a complete (100%) auto-hide option (rather than just peak/pin sidebar).

Tab Tree and Tree Style Tab are currently far more useful add-ons (but they aren't Multiprocess compatible yet):
https://addons.mozilla.org/en-US/firefox/addon/tab-tree/
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

**Comment by bwinton** [comment]
The preview images do need updating, and I believe @johngruen is in the process of updating them.

The thumbnails are exactly as efficient as the previews, though, since if you have enough tabs, they will shrink down to the smaller view.

This add-on is not intended to provide every single option that anyone may want.  It is to test some ideas for putting tabs on the side, and see how they change people's behaviour.

I strongly recommend people use Tree Style Tab if they're looking for something that this add-on doesn't provide!  It's a great add-on, and I'm sure the author will be updating it to add multiprocess compatibility as soon as they can!  Tab Tree is probably similar, but I haven't used that one, myself, so am more hesitant to recommend it.  (For that matter, this add-on will graduate out of Test Pilot in the not-too-distant future, so you should probably look into alternatives now.)

In any case, thank you for your suggestion, but (apart from the things we already have bugs for) I don't think we'll be implementing them.
