### ISSUE TITLE
Sidebar becomes open after (auto) upgrade

### ISSUE THREAD

**Issue by glandium** [bwinton/TabCenter#687]
I always choose to "shrink sidebar when not in use". But every time there is an upgrade of the Tab Center addon (there were two this week), the sidebar returns to the original, open, state.

**Comment by glandium** [comment]
It also seems to lose the "Open tabs above" setting.

**Comment by ericawright** [comment]
@glandium yes, we've made some changes to the default settings this week. Namely - we have changed Tab Center to default to the open state and default to the tabs opening on top. You can change the position the tabs open in the addon's preferences. 
As for the sidebar being opened, I'm hoping it was only because we made some recent changes to it - please open again if you notice it again.

**Comment by glandium** [comment]
Did you change the default settings twice? Because I have two subsequent upgrades that exhibited the problem...

**Comment by ericawright** [comment]
Yes, we did change the default setting twice. (re: the open tabs above/below option, but not re: keeping the drawer pinned open)

**Comment by glandium** [comment]
I got the drawer open twice by an upgrade.

**Comment by glandium** [comment]
I got the drawer open again after today's upgrade.
