### ISSUE TITLE
Expose extensions.verticaltabs.largetabs in extension settings

### ISSUE THREAD

**Issue by nathancahill** [bwinton/TabCenter#708]
Setting this to false improves the extension so much that I think it should be exposed as a setting in the extension settings page, alongside verticaltabs.opentabstop. Thoughts? I can submit a PR if there's interest.

**Comment by bwinton** [comment]
Nope.  🙂 

We're not interested in testing the layout exposed by that preference, which is why it's a hidden preference.  Perhaps, after we're all done in Test Pilot and are retiring the add-on (or, more likely, looking for someone to maintain it), we'll revisit this and probably un-hide the pref, and perhaps even set it to small-tabs by default!  But that's going to be a while from now, and I'm quite sure we won't forget about it in between now and then.  :wink:

Thanks for the offer, though!
