### ISSUE TITLE
"Move tabs to the side" button position should be customizable

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [bwinton/TabCenter#731]
[Affected versions]:
- Nightly 52.0a1
- Tab Center 1.26.0

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to false and latest Tab Center add-on is installed.

[Steps to reproduce]:

1. Open the browser with the profile from prerequisites.
2. Click the "Move tabs on Top" button from the top right side of the Sidebar.
3. Click the Menu button from the browser toolbar and go to Customization.
4. Try to move the "Move tabs to the side" button to a different position.

[Expected result]:
- The button can be moved to a different place, based on user preference.

[Actual result]:
- The button is greyed out and cannot be moved.

[Notes]:
- Seeing as the "New Tab" button can be moved to the left if users wish to do so, I think it would be a good thing for the "Move tabs to the side" button should be customizable.
- Attached a screen recording of the issue.
![move tabs to the side whould be customizable](https://cloud.githubusercontent.com/assets/18304511/19726292/d5259676-9b92-11e6-944d-f5777da520e0.gif)

**Comment by bwinton** [comment]
Since the point of the experiment is to see how many people use Tab Center, having the button be able to be customized away seems like it would go against the princples of the experiment.

(If people really want tabs-on-top, and don't want the button, they should uninstall TabCenter. 😉)

Resolving wontfix, but thanks for the report!
