### ISSUE TITLE
Dead Objects

### ISSUE THREAD

**Issue by ericawright** [bwinton/TabCenter#768]
On Ubuntu  error is generated by disabling and re-enabling TC.

On Win 10 error is generated by toggling top tabs, and by disabling and re-enabling TC.

<img width="835" alt="screen shot 2016-11-07 at 1 18 04 pm" src="https://cloud.githubusercontent.com/assets/10803178/20069914/792dfaee-a4ec-11e6-8849-fbbda363a61d.png">

**Comment by bzbarsky** [comment]
This is coming from resize event listeners that are now dead objects.  Those listeners are added in verticaltabs.js like so:

    window.addEventListener('resize', () => {
      this.resizeTabs();
      document.documentElement.style.setProperty('--pinned-width', `${Math.min(this.pinnedWidth, document.width / 2)}px`);
    }, false);

at a guess, disabling an addon nukes the sandbox this stuff was loaded to, so the window listener becomes a dead object wrapper.

The good news is that the nuking means this leaks a lot less than it would otherwise (just leaks a single entry in the window's listeners, not the entire entrained global).  The bad news is that it still leaks a little bit.  If the extension is notified when it's unloading, it should probably clean up its event listeners.

**Comment by bwinton** [comment]
Yeah, @ericawright's working on a patch that does that…  (Do we know if that's the only one we're leaking?  I'm looking forward to the extra debugging info that will tell us.  :)

**Comment by bzbarsky** [comment]
> Do we know if that's the only one we're leaking?

I don't know for sure.  You could try the patch at https://bug1316067.bmoattachments.org/attachment.cgi?id=8808793 which should give you stacks to "where the event listener got added" in this situation...

**Comment by ericawright** [comment]
Note: they have been significantly reduced after #778, but there are still a few around
