### ISSUE TITLE
pontoon can't commit with the branch protection enabled

### ISSUE THREAD

**Issue by wresuolc** [bwinton/TabCenter#774]
Your master branch has "require at least one approved review" enabled so pontoon can't commit.  At this point:  

* Pontoon can't commit to a different branch, as far as I know
* Pontoon can't make pull requests

Are you comfortable disabling that approval requirement? /cc @mathjazz

**Comment by mathjazz** [comment]
> Pontoon can't commit to a different branch, as far as I know
> Pontoon can't make pull requests

Confirming.

**Comment by bwinton** [comment]
I'm not hugely happy about making the repo less secure.  Are there any plans to add one of those features to Pontoon?

**Comment by mathjazz** [comment]
@bwinton The main reason we prefer to work with the default branch is because we want translations to be available for testing and preview as soon as possible.

However, this doesn't seem to be the case for your project and even if it was, I understand your concern.

Filing a bug to support custom branches:
https://bugzilla.mozilla.org/show_bug.cgi?id=1316273

Until it's fixed, you could also use a separate l10n repository, which would be hooked to Pontoon.

**Comment by bwinton** [comment]
Okay, I've created https://github.com/bwinton/TabCenter-l10n for now, so let's point Pontoon there, and I'll manually merge between them.  (And I'll close this when that is all set up.  🙂)

**Comment by mathjazz** [comment]
It works!
https://github.com/bwinton/TabCenter-l10n/commit/256972db474efd1782c53dd5a99d786d349cb6d6

Thank you! :)

**Comment by bwinton** [comment]
Okay, I'll make a note to merge the locales in periodically.  🙂  Thanks for your help!

**Comment by mathjazz** [comment]
And if there's anything else we can do to make your life easier easier, let us know!

**Comment by bwinton** [comment]
If any of the localizers feels like making pull requests from the l10n repo to this one when stuff changes, that would be a big help!  (And I'm happy to add more people as collaborators to that repo. 🙂)
