### ISSUE TITLE
[Feature Request] add preference to force condensed view

### ISSUE THREAD

**Issue by mikehenrty** [bwinton/TabCenter#814]
I find the condensed view with only website favicons and page titles to be much easier to scan than the expanded page preview view. It would be great to have a preference to force the condensed view. If the authors don't disagree, I can take a stab at implementing this myself.

**Comment by bwinton** [comment]
It's already implemented, behind [a hidden pref](https://github.com/bwinton/TabCenter/blob/master/package.json#L149) because we don't want people to change it and mess up the results of the experiment.
Thanks for the offer, though!  🙂

**Comment by mikehenrty** [comment]
Got it, thanks for the info.

If you're still reading this, how does adding a pref mess up the results of the experiment? To me it gives more granular learnings, as it allows people to "vote with their feet" for this feature. I feel people are more likely to flip a switch, than find the online feedback form and fill in a text box about a particular feature.

**Comment by bwinton** [comment]
We expect people will have different behaviour with the condensed view as compared with the expanded view, and we're only interested in their behaviour in the expanded view at this time.  (The hidden pref is there mostly to stop people insisting we add it.  😉  Once we graduate from Test Pilot, we'll probably expose the pref, since then we won't care so much about tracking how people use the feature.)

**Comment by mikehenrty** [comment]
Makes sense. I appreciate the info. Also appreciate the test pilot program :)
