### ISSUE TITLE
Don't reverse pinned tabs

### ISSUE THREAD

**Issue by heftig** [bwinton/TabCenter#817]
When the tab order is reversed, I would like pinned tabs to not be reordered, so they do not reverse when switching between tabs-on-top and tabs-on-side.

**Comment by SoftVision-PaulOiegas** [comment]
I think it depends on individual. If you look from the perspective of having the last opened tab always on top, then it makes sense to have also the latest pinned tab on top. Judging from this point of view, the behavior seems normal. Also, it could help people that have a long list of pinned tabs.

If the dev team will consider to have the pinned tabs separately ordered from the normal tabs, then you'll need to add another option for this because probably someone will complain after the change. I don't know if it worth to complicate the code with this, but only the dev team could only answer this.
