### ISSUE TITLE
Scroll position jumps to previous tab after selecting a far away tab.

### ISSUE THREAD

**Issue by yousifucv** [bwinton/TabCenter#853]
Imagine I have 50 tabs open.
Currently my tab view is at the top, I see the first top tabs on the list.
I scroll down far to find another tab, I click on it, then... the tab view jumps back to where the previous tab was (at the top), but the tab that I clicked is rendered.

**Comment by SoftVision-PaulOiegas** [comment]
Hi @yousifucv and thanks for reporting this issue ! 
I have tried to reproduce it but to be honest, I had no luck. Can you please check what version is your Tab Center addon in "about:addons" page on "Extensions" tab ? 

Also, by any chance is your issue something similar with this one #841 ? If yes, the issue was fixed in development but hasn't reached yet the production build you find on https:://testpilot.firefox.com website.

**Comment by yousifucv** [comment]
It was version 1.21. I updated, and it's not longer an issue!
Thanks! Sorry I thought I checked to see if it was the latest version.
One scary thing though, is after I updated, all the tabs disappeared (the side bar was blank, New Tab button did nothing) and the top window bar disappeared too (The bar that has the minimize, maximize, close button). But I restarted the browser and everything was restored. So it wasn't an issue, it just worried me.

Anyway, thank you for your help.
