### ISSUE TITLE
Update disabled tabcenter, can't enable

### ISSUE THREAD

**Issue by hesselink** [bwinton/TabCenter#856]
I just updated Firefox to 50.1.0, and after restarting, tab center was suddenly disabled. When trying to enable it again, it just shows 'Enabling' forever, similar to #842.

Firefox 50.1.0, MacOS 10.10.5

**Comment by hesselink** [comment]
Uninstalled test pilot, reinstalled, and now I could enable tab center again. Feel free to close, or let me know if I can do anything to help investigate.

**Comment by chris-morgan** [comment]
I run Nightly and have had Test Pilot installed for ages and had Tab Center installed in the past. I wanted to try it again, but it was hanging at “Enabling…” Disabling and reenabling Test Pilot did nothing. Uninstalling and reinstalling Test Pilot worked. So now I can have Tab Center installed.

This sounds like a Test Pilot bug rather than a Tab Center bug.

My first impressions are that I might actually be able to live with Tab Center in lieu of Tree Style Tab this time. Yay! (Plus Tree Style Tab was being *horrifically* slow for me on only a couple of hundred tabs.)
