### ISSUE TITLE
Stuck while Enabling the plugin

### ISSUE THREAD

**Issue by tmahmood** [bwinton/TabCenter#858]
Using the Latest Firefox Nightly 53.0a1 (2016-12-22) (64-bit)
Linux 4.8.13-1-ARCH #1 SMP PREEMPT  x86_64 GNU/Linux

What I do:
1. Go to: https://testpilot.firefox.com/experiments/tab-center
2. Click Enable

Expected result: Extension gets installed
What happens: stuck at "Enabling ..." animation waited over 10 minutes

Turned off Tracking Protection Add-on, Does not work.
Turned off UBlock for the site, Does not work.

I'll try to provide any information required. 

Thank you

**Comment by SoftVision-PaulOiegas** [comment]
@tmahmood Thanks for reporting the issue ! This seems to be caused by an Test Pilot auto update issue. Please navigate to about:addons page and from Extensions tab, click the top right settings cog wheel and choose to check for updates.  Afterwards, if Test Pilot is updated,  Tab Center enabling should work. 
However, if the browser does not find an update for Test Pilot, please reinstall it.

Let me know if this fixed your issue.

**Comment by tmahmood** [comment]
This solved the issue for me. 

Thank you very much!
