### ISSUE TITLE
Show Tab-URL in the bottom-bar

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bwinton/TabCenter#859]
Missing the Tab-URL (e.g. for all my Facebook-Tabs) in the bottom-bar like I have it with normal tabs.

**Comment by ericawright** [comment]
Could you provide a screenshot of how it is with normal tabs, just to give a better idea of what you are requesting?

**Comment by SoftVision-PaulOiegas** [comment]
@Tobias-B-Besemer You mean that if you hover your tabs the URL is not displayed in the bottom left part of the browser ? If yes, I think you are confusing the link hover with tab hover. Only when you hover links on a page the URL is displayed on bottom left part of the browser. 
For tabs, I don't think this was ever available in Firefox. Also, this is not available on Chrome either.

**Comment by Tobias-B-Besemer** [comment]
Yes, I mean that if I hover my tabs the URL is not displayed in the bottom left part of the browser.
It's tab hover ut only with the tabs shown in the "more tabs arrow".
But I can't make a screenshot because the Alt key of my shortcut close the arrow.
Should be also a bug in FF because it's only available in the "more tabs arrow".

**Comment by Tobias-B-Besemer** [comment]
Please look also here: https://bugzilla.mozilla.org/show_bug.cgi?id=1359181

**Comment by SoftVision-PaulOiegas** [comment]
@Tobias-B-Besemer I think I wasn't clear enough. As far as I know, none of the most known browser (Chrome, Opera, Safari) is doing what you ask by default. Unless you are using some kind of an add-on that does that for you. 
If you hover the tabs, you may get only a tooltip with the page name next to your mouse. But not the page URL in the bottom part of the browser.

**Only** if you hover a link from a page you will get the URL in the bottom part.

I'm sorry, but I have to close this as invalid since this is the normal behavior of the browser. Unless you are asking for an enhancement here.
