### ISSUE TITLE
"Hide Tab Bar With One Tab" add-on not compatible

### ISSUE THREAD

**Issue by Keith94** [bwinton/TabCenter#862]
https://addons.mozilla.org/en-US/firefox/addon/hide-tab-bar-with-one-tab/

Any clue why it doesn't work with Tab Center? Maybe there's an easy fix.

**Comment by ericawright** [comment]
I don't see any problem with it when tab center is in side tab mode (using mac). But when it is toggled to top tab mode the icon gets appended to #TabsToolbar, which is then hidden by "Hide Tab Bar With One Tab" so you are unable to toggle back until opening a second tab.

Looks like it could be fixed fairly easily if someone else wanted to give it a shot. The problem seems to me to be finding a spot to put the icon when it is in top tabs mode.

**Comment by Keith94** [comment]
That's strange, because for me the #verticaltabs-box is not hidden at all when there is only one tab. Is it different on Windows? (I'm on Windows 8).

**Comment by ericawright** [comment]
oh, I suppose I was misunderstanding what you meant by "not working" I was only thinking of how the #TabsToolbar element is hidden. Which, it is when TC is in side tabs mode. in that case there are 2 issues. 
Since their addon does not know about the #verticaltabs-box, (it was created by Tab Center) they do not know that it should be hidden. This could probably be easily changed by their addon. 
1. the icon is missing in top tabs mode
2. #verticaltabs-box should be hidden altogether

**Comment by Keith94** [comment]
>This could probably be easily changed by their addon.

Yeah, I'm curious how that add-on can be modified to hide the #verticaltabs-box as well. Not sure if the developer is updating it anymore.

**Comment by ericawright** [comment]
closing to track these types of issues in  #464
