### ISSUE TITLE
Tooltips are in incorrect language.

### ISSUE THREAD

**Issue by AmyAmy** [bwinton/TabCenter#992]
I'm running Firefox Developer Edition (64 bit) in English (en-gb), however.
Tabcentre shows in English exept for tooltips, which display in Dutch(!).

![image](https://cloud.githubusercontent.com/assets/630387/23611551/35c4c9e2-0278-11e7-8217-437147286ae2.png)

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @AmyAmy, thanks for reporting this.

This happens because our locales fall back to dutch, in your case, when they fail to get en-gb and en.

@ericawright, the Test Pilot team had a [similar issue](https://github.com/mozilla/testpilot/issues/2006) and they fixed it like [this](https://github.com/mozilla/testpilot/pull/2016).

**Comment by SoftVision-PaulOiegas** [comment]
I'm not sure the fix covered entirely the problem. 
- If you have the "Content" languages are set as "[en-GB] > [en] > [nl]" The tooltips and context menu options are correctly displayed in English.
- If the "Content" languages are set as "[en-GB] > [nl] > [en]", the tooltips and context menu options are still displayed in Dutch.

Based on my logic, even if the second language set is Dutch, the content should fallback to English since first option is "[en-GB]". At least this is what we did on Test Pilot website if I remember well.

**Comment by ericawright** [comment]
@SoftVision-PaulOiegas But if the user has set their language preferences to  "[en-GB] > [nl] > [en]" I think it's okay that it goes to Dutch before generic en, since we don't actually have an en-GB. It seems to me that that is what the user has requested - if no en-GB prefer dutch over generic English.

**Comment by SoftVision-PaulOiegas** [comment]
You're right. It seams that I remembered wrong. After some diggings made on the TxP repo it seams that we did the same thing on Test Pilot.
I was thinking that even if I'm GB user, I would prefer [en-US] instead of Dutch if my main option is [en-GB].
Hope this fixes @AmyAmy 's issue.
