### ISSUE TITLE
Tabs and go back button

### ISSUE THREAD

**Issue by tomassykora** [bwinton/TabCenter#994]
Hi,

this is actually not an issue, just a little note. When I want to click on go back button, I often move the mouse to the tab area, so the tabs show up and hide the go back button which is really very annoying if it happens often. I talked to colleagues of mine and they see it the same way. It would be nice to figure something out to prevent this.

Thank for your work,
Tomas Sykora

**Comment by SoftVision-PaulOiegas** [comment]
Hi @tomassykora and thanks for your report. Sadly, I'm not sure there is something that the developers can do here... This will always be the disadvantage of "auto-hide" option in any case, not only on Tab Center. 
I personally like more the fixed width for the sidebar since I was experiencing the same behavior as yours. 

We had some other reports of users that wanted to move the sidebar under the address bar. Maybe that could help since the sidebar would be under the back button. Also right now the developers are thinking to remove the titlebar for more space. You can jump into the discussion maybe if you have an opinion / idea about this in bug #717.

**Comment by hcs64** [comment]
Just another voice on this point, it's easy to slam the mouse the left edge of the screen and hit the back button. Tab Center on the side makes it a much smaller target, virtually. I've tried to get used to this but it has become sufficiently frustrating that I've put the tabs back up top. Unfortunately I don't have a good solution.

**Comment by SoftVision-PaulOiegas** [comment]
Well, I personally use it with fixed width because I always need to see the tab names. 
And on a 24 inch monitor, most of the sites have large unused spaces on both sides... so no loss of website content in my case.
