### ISSUE TITLE
Search field cleared when I try to delete a tab

### ISSUE THREAD

**Issue by wlach** [bwinton/TabCenter#999]
To reproduce:

* Search for something (e.g. "linux") that only a subset of your tab titles will have
* Attempt to remove one of those tabs while search filter is in place

Expected:

* Tab will be removed, search filter stays in place

Actual:

* Search filter gets cleared, tab not removed

**Comment by ericawright** [comment]
The search field being cleared was a decision that we made under the assumption that once you add or delete a tab your intentions have changed and wouldn't want the search any more - but I understand wanting it to remain - I think it's worth considering.
For me, the search field gets cleared and the tab also gets deleted. Do you have anything that might be interfering with the tab being deleted? Can you also let me know your OS and Firefox version?

**Comment by wlach** [comment]
Hmm, on second try I think the tab does get deleted, it was just hard to see it happen since the search gets cleared and the state gets reset.

**Comment by ericawright** [comment]
this is being changed in our next release

**Comment by SoftVision-PaulOiegas** [comment]
Verified this behavior in the RC v1.33 build you provided and it seems to be working well. If you have multiple tabs with the entered string, the filtering is kept and closed tab is properly removed.
If you only have a single tab that matches your filter, then the tab is closed, filtering is cleared and all tabs are displayed because of that.

To me, this seems to be the best behavior. However, we're gonna further test this to make sure that this fix didn't introduced anything new.
